### ISSUE TITLE
Checkstyle's "LineLength" fails on Intellij, leading to hard to diagnose error

### ISSUE THREAD

**Issue by thePalindrome** [jriwanek/ForgeModdingSkeleton#22]
When building, it will be claimed that 

```
Execution failed for task ':checkstyleMain'.
> Unable to create Root Module: config -snipped for berevity-
```

The real error is:

```
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: LineLength is not allowed as a child in Checker
        at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:497)
        at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:198)
        at com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTask.createRootModule(CheckstyleAntTask.java:412)
        ... 65 more
```

The solution is to simply comment out the module for LineLength in config/checkstyle/checkstyle.xml

There *may* be a better way to get it working.

**Comment by KiriCattus** [comment]
I thought I had PRd a fix in for that a while back but the fix I had does not work for everywhere else but intellij, from what I've been reading though they updated the plugin/tool to work differently but I can't understand how myself..

It might be a good idea to check the google or sun defaults that FMSs checkstyle is sorta forked from then update it that way to see if it has fixes we don't yet have

**Comment by jriwanek** [comment]
Fixed
